apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: service-a
spec:
  destination:
    namespace: tenant1
    server: https://kubernetes.default.svc
  project: argocd
  source:
    chart: service-a
    helm:
      valueFiles:
      - ue2-dev-values.yaml
      values: |
        examplekey: customvalue
    repoURL: https://tht.helm-repo.example.com/repository/dev
    targetRevision: '*'
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 1m0s
      limit: 1
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
